package com.hykd.models;

import io.jboot.db.annotation.Table;
import com.hykd.models.base.BaseMp;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mp", primaryKey = "id")
public class Mp extends BaseMp<Mp> {
	
}
